### ISSUE TITLE
Link VC runtime statically for windows

### ISSUE THREAD

**Issue by pacman82** [blue-yonder/di-csv2xml#8]
```toml
[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static", "-Zunstable-options"]
```
